In [23]:
import numpy as np
import os
import pandas as pd
import requests
from dotenv import load_dotenv

pd.set_option('display.max_rows', None)

In [4]:
# Load and get api key from .env
api_key = os.getenv("API_KEY")

In [48]:
food_query = 'chicken'
r = requests.get(f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={api_key}&query={food_query}&dataType=Foundation')

In [49]:
data = r.json()

In [50]:
data['foods']

[{'fdcId': 2514746,
  'description': 'Chicken, ground, with additives, raw',
  'commonNames': '',
  'additionalDescriptions': '',
  'dataType': 'Foundation',
  'ndbNumber': 5332,
  'publishedDate': '2023-04-20',
  'foodCategory': 'Poultry Products',
  'mostRecentAcquisitionDate': '2023-01-09',
  'allHighlightFields': '',
  'score': 201.99571,
  'microbes': [],
  'foodNutrients': [{'nutrientId': 1089,
    'nutrientName': 'Iron, Fe',
    'nutrientNumber': '303',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.593,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5400,
    'indentLevel': 1,
    'foodNutrientId': 31223306,
    'dataPoints': 8,
    'min': 0.351,
    'max': 0.724,
    'median': 0.669},
   {'nutrientId': 1090,
    'nutrientName': 'Magnesium, Mg',
    'nutrientNumber': '304',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 20.5,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5500,
    'indentLevel': 1,
    'foodNutrientId': 31223307,
    'dataPoints': 8,
    'min': 17.5,
    'max': 26.1,
    'median': 19.4},
   {'nutrientId': 1091,
    'nutrientName': 'Phosphorus, P',
    'nutrientNumber': '305',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 166,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5600,
    'indentLevel': 1,
    'foodNutrientId': 31223308,
    'dataPoints': 8,
    'min': 142,
    'max': 199,
    'median': 160},
   {'nutrientId': 1092,
    'nutrientName': 'Potassium, K',
    'nutrientNumber': '306',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 302,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5700,
    'indentLevel': 1,
    'foodNutrientId': 31223309,
    'dataPoints': 8,
    'min': 231,
    'max': 376,
    'median': 287},
   {'nutrientId': 1253,
    'nutrientName': 'Cholesterol',
    'nutrientNumber': '601',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 81.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15700,
    'indentLevel': 1,
    'foodNutrientId': 31223310,
    'dataPoints': 8,
    'min': 71.9,
    'max': 96.3,
    'median': 80.0},
   {'nutrientId': 1093,
    'nutrientName': 'Sodium, Na',
    'nutrientNumber': '307',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 63.0,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5800,
    'indentLevel': 1,
    'foodNutrientId': 31223311,
    'dataPoints': 8,
    'min': 37.6,
    'max': 96.1,
    'median': 55.3},
   {'nutrientId': 1095,
    'nutrientName': 'Zinc, Zn',
    'nutrientNumber': '309',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.18,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5900,
    'indentLevel': 1,
    'foodNutrientId': 31223312,
    'dataPoints': 8,
    'min': 0.596,
    'max': 1.54,
    'median': 1.26},
   {'nutrientId': 1098,
    'nutrientName': 'Copper, Cu',
    'nutrientNumber': '312',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.0362,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6000,
    'indentLevel': 1,
    'foodNutrientId': 31223313,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0545,
    'median': 0.0446},
   {'nutrientId': 1002,
    'nutrientName': 'Nitrogen',
    'nutrientNumber': '202',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 2.87,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 500,
    'indentLevel': 1,
    'foodNutrientId': 31223314,
    'dataPoints': 8,
    'min': 2.57,
    'max': 3.47,
    'median': 2.71},
   {'nutrientId': 1004,
    'nutrientName': 'Total lipid (fat)',
    'nutrientNumber': '204',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 7.16,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 800,
    'indentLevel': 1,
    'foodNutrientId': 31223315,
    'dataPoints': 8,
    'min': 2.12,
    'max': 11.0,
    'median': 7.83},
   {'nutrientId': 1101,
    'nutrientName': 'Manganese, Mn',
    'nutrientNumber': '315',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00502,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6100,
    'indentLevel': 1,
    'foodNutrientId': 31223316,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0139,
    'median': 0.0},
   {'nutrientId': 1007,
    'nutrientName': 'Ash',
    'nutrientNumber': '207',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.969,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 1000,
    'indentLevel': 1,
    'foodNutrientId': 31223317,
    'dataPoints': 8,
    'min': 0.86,
    'max': 1.17,
    'median': 0.955},
   {'nutrientId': 1051,
    'nutrientName': 'Water',
    'nutrientNumber': '255',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 74.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 100,
    'indentLevel': 1,
    'foodNutrientId': 31223318,
    'dataPoints': 8,
    'min': 72.3,
    'max': 76.1,
    'median': 74.8},
   {'nutrientId': 1087,
    'nutrientName': 'Calcium, Ca',
    'nutrientNumber': '301',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 5.82,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5300,
    'indentLevel': 1,
    'foodNutrientId': 31223319,
    'dataPoints': 8,
    'min': 4.07,
    'max': 7.82,
    'median': 5.42},
   {'nutrientId': 1003,
    'nutrientName': 'Protein',
    'nutrientNumber': '203',
    'unitName': 'G',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 17.9,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 600,
    'indentLevel': 1,
    'foodNutrientId': 31223374,
    'min': 16.1,
    'max': 21.7,
    'median': 16.9},
   {'nutrientId': 1005,
    'nutrientName': 'Carbohydrate, by difference',
    'nutrientNumber': '205',
    'unitName': 'G',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 0.0,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 1110,
    'indentLevel': 2,
    'foodNutrientId': 31223375},
   {'nutrientId': 2047,
    'nutrientName': 'Energy (Atwater General Factors)',
    'nutrientNumber': '957',
    'unitName': 'KCAL',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 133,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 280,
    'indentLevel': 1,
    'foodNutrientId': 31223376},
   {'nutrientId': 2048,
    'nutrientName': 'Energy (Atwater Specific Factors)',
    'nutrientNumber': '958',
    'unitName': 'KCAL',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 138,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 290,
    'indentLevel': 1,
    'foodNutrientId': 31223377},
   {'nutrientId': 1293,
    'nutrientName': 'Fatty acids, total polyunsaturated',
    'nutrientNumber': '646',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.38,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 12900,
    'indentLevel': 1,
    'foodNutrientId': 33291411,
    'dataPoints': 8,
    'min': 0.27,
    'max': 2.6,
    'median': 1.46},
   {'nutrientId': 1292,
    'nutrientName': 'Fatty acids, total monounsaturated',
    'nutrientNumber': '645',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 2.17,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 11400,
    'indentLevel': 1,
    'foodNutrientId': 33291412,
    'dataPoints': 8,
    'min': 0.41,
    'max': 3.67,
    'median': 2.45},
   {'nutrientId': 1257,
    'nutrientName': 'Fatty acids, total trans',
    'nutrientNumber': '605',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.021,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15400,
    'indentLevel': 1,
    'foodNutrientId': 33291413,
    'dataPoints': 8,
    'min': 0.01,
    'max': 0.03,
    'median': 0.02},
   {'nutrientId': 1258,
    'nutrientName': 'Fatty acids, total saturated',
    'nutrientNumber': '606',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.56,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 9700,
    'indentLevel': 1,
    'foodNutrientId': 33291414,
    'dataPoints': 8,
    'min': 0.34,
    'max': 2.55,
    'median': 1.72}],
  'finalFoodInputFoods': [],
  'foodMeasures': [],
  'foodAttributes': [],
  'foodAttributeTypes': [],
  'foodVersionIds': []},
 {'fdcId': 2646170,
  'description': 'Chicken, breast, boneless, skinless, raw',
  'commonNames': '',
  'additionalDescriptions': '',
  'dataType': 'Foundation',
  'ndbNumber': 100304,
  'publishedDate': '2023-10-26',
  'foodCategory': 'Poultry Products',
  'mostRecentAcquisitionDate': '2023-04-03',
  'allHighlightFields': '',
  'score': 187.15979,
  'microbes': [],
  'foodNutrients': [{'nutrientId': 1089,
    'nutrientName': 'Iron, Fe',
    'nutrientNumber': '303',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.354,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5400,
    'indentLevel': 1,
    'foodNutrientId': 33295209,
    'dataPoints': 8,
    'min': 0.304,
    'max': 0.413,
    'median': 0.352},
   {'nutrientId': 1090,
    'nutrientName': 'Magnesium, Mg',
    'nutrientNumber': '304',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 26.2,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5500,
    'indentLevel': 1,
    'foodNutrientId': 33295210,
    'dataPoints': 8,
    'min': 23.0,
    'max': 29.7,
    'median': 26.6},
   {'nutrientId': 1091,
    'nutrientName': 'Phosphorus, P',
    'nutrientNumber': '305',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 215,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5600,
    'indentLevel': 1,
    'foodNutrientId': 33295211,
    'dataPoints': 8,
    'min': 200,
    'max': 226,
    'median': 213},
   {'nutrientId': 1092,
    'nutrientName': 'Potassium, K',
    'nutrientNumber': '306',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 330,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5700,
    'indentLevel': 1,
    'foodNutrientId': 33295212,
    'dataPoints': 8,
    'min': 290,
    'max': 359,
    'median': 332},
   {'nutrientId': 1253,
    'nutrientName': 'Cholesterol',
    'nutrientNumber': '601',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 72.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15700,
    'indentLevel': 1,
    'foodNutrientId': 33295213,
    'dataPoints': 8,
    'min': 64.0,
    'max': 83.4,
    'median': 72.8},
   {'nutrientId': 1093,
    'nutrientName': 'Sodium, Na',
    'nutrientNumber': '307',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 65.8,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5800,
    'indentLevel': 1,
    'foodNutrientId': 33295214,
    'dataPoints': 8,
    'min': 48.9,
    'max': 84.8,
    'median': 66.7},
   {'nutrientId': 1095,
    'nutrientName': 'Zinc, Zn',
    'nutrientNumber': '309',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.654,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5900,
    'indentLevel': 1,
    'foodNutrientId': 33295215,
    'dataPoints': 8,
    'min': 0.555,
    'max': 0.796,
    'median': 0.624},
   {'nutrientId': 1257,
    'nutrientName': 'Fatty acids, total trans',
    'nutrientNumber': '605',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00875,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15400,
    'indentLevel': 1,
    'foodNutrientId': 33295216,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.01,
    'median': 0.01},
   {'nutrientId': 1098,
    'nutrientName': 'Copper, Cu',
    'nutrientNumber': '312',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00364,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6000,
    'indentLevel': 1,
    'foodNutrientId': 33295217,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0291,
    'median': 0.0},
   {'nutrientId': 1002,
    'nutrientName': 'Nitrogen',
    'nutrientNumber': '202',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 3.6,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 500,
    'indentLevel': 1,
    'foodNutrientId': 33295218,
    'dataPoints': 8,
    'min': 3.45,
    'max': 3.74,
    'median': 3.6},
   {'nutrientId': 1258,
    'nutrientName': 'Fatty acids, total saturated',
    'nutrientNumber': '606',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.349,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 9700,
    'indentLevel': 1,
    'foodNutrientId': 33295219,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.6,
    'median': 0.34},
   {'nutrientId': 1004,
    'nutrientName': 'Total lipid (fat)',
    'nutrientNumber': '204',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.93,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 800,
    'indentLevel': 1,
    'foodNutrientId': 33295220,
    'dataPoints': 8,
    'min': 1.31,
    'max': 3.1,
    'median': 1.71},
   {'nutrientId': 1292,
    'nutrientName': 'Fatty acids, total monounsaturated',
    'nutrientNumber': '645',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.369,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 11400,
    'indentLevel': 1,
    'foodNutrientId': 33295221,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.71,
    'median': 0.335},
   {'nutrientId': 1101,
    'nutrientName': 'Manganese, Mn',
    'nutrientNumber': '315',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.0,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6100,
    'indentLevel': 1,
    'foodNutrientId': 33295222,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0,
    'median': 0.0},
   {'nutrientId': 1293,
    'nutrientName': 'Fatty acids, total polyunsaturated',
    'nutrientNumber': '646',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.296,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 12900,
    'indentLevel': 1,
    'foodNutrientId': 33295223,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.55,
    'median': 0.275},
   {'nutrientId': 1007,
    'nutrientName': 'Ash',
    'nutrientNumber': '207',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,

In [51]:
data['foods']

[{'fdcId': 2514746,
  'description': 'Chicken, ground, with additives, raw',
  'commonNames': '',
  'additionalDescriptions': '',
  'dataType': 'Foundation',
  'ndbNumber': 5332,
  'publishedDate': '2023-04-20',
  'foodCategory': 'Poultry Products',
  'mostRecentAcquisitionDate': '2023-01-09',
  'allHighlightFields': '',
  'score': 201.99571,
  'microbes': [],
  'foodNutrients': [{'nutrientId': 1089,
    'nutrientName': 'Iron, Fe',
    'nutrientNumber': '303',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.593,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5400,
    'indentLevel': 1,
    'foodNutrientId': 31223306,
    'dataPoints': 8,
    'min': 0.351,
    'max': 0.724,
    'median': 0.669},
   {'nutrientId': 1090,
    'nutrientName': 'Magnesium, Mg',
    'nutrientNumber': '304',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 20.5,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5500,
    'indentLevel': 1,
    'foodNutrientId': 31223307,
    'dataPoints': 8,
    'min': 17.5,
    'max': 26.1,
    'median': 19.4},
   {'nutrientId': 1091,
    'nutrientName': 'Phosphorus, P',
    'nutrientNumber': '305',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 166,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5600,
    'indentLevel': 1,
    'foodNutrientId': 31223308,
    'dataPoints': 8,
    'min': 142,
    'max': 199,
    'median': 160},
   {'nutrientId': 1092,
    'nutrientName': 'Potassium, K',
    'nutrientNumber': '306',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 302,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5700,
    'indentLevel': 1,
    'foodNutrientId': 31223309,
    'dataPoints': 8,
    'min': 231,
    'max': 376,
    'median': 287},
   {'nutrientId': 1253,
    'nutrientName': 'Cholesterol',
    'nutrientNumber': '601',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 81.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15700,
    'indentLevel': 1,
    'foodNutrientId': 31223310,
    'dataPoints': 8,
    'min': 71.9,
    'max': 96.3,
    'median': 80.0},
   {'nutrientId': 1093,
    'nutrientName': 'Sodium, Na',
    'nutrientNumber': '307',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 63.0,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5800,
    'indentLevel': 1,
    'foodNutrientId': 31223311,
    'dataPoints': 8,
    'min': 37.6,
    'max': 96.1,
    'median': 55.3},
   {'nutrientId': 1095,
    'nutrientName': 'Zinc, Zn',
    'nutrientNumber': '309',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.18,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5900,
    'indentLevel': 1,
    'foodNutrientId': 31223312,
    'dataPoints': 8,
    'min': 0.596,
    'max': 1.54,
    'median': 1.26},
   {'nutrientId': 1098,
    'nutrientName': 'Copper, Cu',
    'nutrientNumber': '312',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.0362,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6000,
    'indentLevel': 1,
    'foodNutrientId': 31223313,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0545,
    'median': 0.0446},
   {'nutrientId': 1002,
    'nutrientName': 'Nitrogen',
    'nutrientNumber': '202',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 2.87,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 500,
    'indentLevel': 1,
    'foodNutrientId': 31223314,
    'dataPoints': 8,
    'min': 2.57,
    'max': 3.47,
    'median': 2.71},
   {'nutrientId': 1004,
    'nutrientName': 'Total lipid (fat)',
    'nutrientNumber': '204',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 7.16,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 800,
    'indentLevel': 1,
    'foodNutrientId': 31223315,
    'dataPoints': 8,
    'min': 2.12,
    'max': 11.0,
    'median': 7.83},
   {'nutrientId': 1101,
    'nutrientName': 'Manganese, Mn',
    'nutrientNumber': '315',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00502,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6100,
    'indentLevel': 1,
    'foodNutrientId': 31223316,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0139,
    'median': 0.0},
   {'nutrientId': 1007,
    'nutrientName': 'Ash',
    'nutrientNumber': '207',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.969,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 1000,
    'indentLevel': 1,
    'foodNutrientId': 31223317,
    'dataPoints': 8,
    'min': 0.86,
    'max': 1.17,
    'median': 0.955},
   {'nutrientId': 1051,
    'nutrientName': 'Water',
    'nutrientNumber': '255',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 74.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 100,
    'indentLevel': 1,
    'foodNutrientId': 31223318,
    'dataPoints': 8,
    'min': 72.3,
    'max': 76.1,
    'median': 74.8},
   {'nutrientId': 1087,
    'nutrientName': 'Calcium, Ca',
    'nutrientNumber': '301',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 5.82,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5300,
    'indentLevel': 1,
    'foodNutrientId': 31223319,
    'dataPoints': 8,
    'min': 4.07,
    'max': 7.82,
    'median': 5.42},
   {'nutrientId': 1003,
    'nutrientName': 'Protein',
    'nutrientNumber': '203',
    'unitName': 'G',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 17.9,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 600,
    'indentLevel': 1,
    'foodNutrientId': 31223374,
    'min': 16.1,
    'max': 21.7,
    'median': 16.9},
   {'nutrientId': 1005,
    'nutrientName': 'Carbohydrate, by difference',
    'nutrientNumber': '205',
    'unitName': 'G',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 0.0,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 1110,
    'indentLevel': 2,
    'foodNutrientId': 31223375},
   {'nutrientId': 2047,
    'nutrientName': 'Energy (Atwater General Factors)',
    'nutrientNumber': '957',
    'unitName': 'KCAL',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 133,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 280,
    'indentLevel': 1,
    'foodNutrientId': 31223376},
   {'nutrientId': 2048,
    'nutrientName': 'Energy (Atwater Specific Factors)',
    'nutrientNumber': '958',
    'unitName': 'KCAL',
    'derivationCode': 'NC',
    'derivationDescription': 'Calculated',
    'derivationId': 49,
    'value': 138,
    'foodNutrientSourceId': 2,
    'foodNutrientSourceCode': '4',
    'foodNutrientSourceDescription': 'Calculated or imputed',
    'rank': 290,
    'indentLevel': 1,
    'foodNutrientId': 31223377},
   {'nutrientId': 1293,
    'nutrientName': 'Fatty acids, total polyunsaturated',
    'nutrientNumber': '646',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.38,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 12900,
    'indentLevel': 1,
    'foodNutrientId': 33291411,
    'dataPoints': 8,
    'min': 0.27,
    'max': 2.6,
    'median': 1.46},
   {'nutrientId': 1292,
    'nutrientName': 'Fatty acids, total monounsaturated',
    'nutrientNumber': '645',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 2.17,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 11400,
    'indentLevel': 1,
    'foodNutrientId': 33291412,
    'dataPoints': 8,
    'min': 0.41,
    'max': 3.67,
    'median': 2.45},
   {'nutrientId': 1257,
    'nutrientName': 'Fatty acids, total trans',
    'nutrientNumber': '605',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.021,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15400,
    'indentLevel': 1,
    'foodNutrientId': 33291413,
    'dataPoints': 8,
    'min': 0.01,
    'max': 0.03,
    'median': 0.02},
   {'nutrientId': 1258,
    'nutrientName': 'Fatty acids, total saturated',
    'nutrientNumber': '606',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.56,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 9700,
    'indentLevel': 1,
    'foodNutrientId': 33291414,
    'dataPoints': 8,
    'min': 0.34,
    'max': 2.55,
    'median': 1.72}],
  'finalFoodInputFoods': [],
  'foodMeasures': [],
  'foodAttributes': [],
  'foodAttributeTypes': [],
  'foodVersionIds': []},
 {'fdcId': 2646170,
  'description': 'Chicken, breast, boneless, skinless, raw',
  'commonNames': '',
  'additionalDescriptions': '',
  'dataType': 'Foundation',
  'ndbNumber': 100304,
  'publishedDate': '2023-10-26',
  'foodCategory': 'Poultry Products',
  'mostRecentAcquisitionDate': '2023-04-03',
  'allHighlightFields': '',
  'score': 187.15979,
  'microbes': [],
  'foodNutrients': [{'nutrientId': 1089,
    'nutrientName': 'Iron, Fe',
    'nutrientNumber': '303',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.354,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5400,
    'indentLevel': 1,
    'foodNutrientId': 33295209,
    'dataPoints': 8,
    'min': 0.304,
    'max': 0.413,
    'median': 0.352},
   {'nutrientId': 1090,
    'nutrientName': 'Magnesium, Mg',
    'nutrientNumber': '304',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 26.2,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5500,
    'indentLevel': 1,
    'foodNutrientId': 33295210,
    'dataPoints': 8,
    'min': 23.0,
    'max': 29.7,
    'median': 26.6},
   {'nutrientId': 1091,
    'nutrientName': 'Phosphorus, P',
    'nutrientNumber': '305',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 215,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5600,
    'indentLevel': 1,
    'foodNutrientId': 33295211,
    'dataPoints': 8,
    'min': 200,
    'max': 226,
    'median': 213},
   {'nutrientId': 1092,
    'nutrientName': 'Potassium, K',
    'nutrientNumber': '306',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 330,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5700,
    'indentLevel': 1,
    'foodNutrientId': 33295212,
    'dataPoints': 8,
    'min': 290,
    'max': 359,
    'median': 332},
   {'nutrientId': 1253,
    'nutrientName': 'Cholesterol',
    'nutrientNumber': '601',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 72.7,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15700,
    'indentLevel': 1,
    'foodNutrientId': 33295213,
    'dataPoints': 8,
    'min': 64.0,
    'max': 83.4,
    'median': 72.8},
   {'nutrientId': 1093,
    'nutrientName': 'Sodium, Na',
    'nutrientNumber': '307',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 65.8,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5800,
    'indentLevel': 1,
    'foodNutrientId': 33295214,
    'dataPoints': 8,
    'min': 48.9,
    'max': 84.8,
    'median': 66.7},
   {'nutrientId': 1095,
    'nutrientName': 'Zinc, Zn',
    'nutrientNumber': '309',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.654,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 5900,
    'indentLevel': 1,
    'foodNutrientId': 33295215,
    'dataPoints': 8,
    'min': 0.555,
    'max': 0.796,
    'median': 0.624},
   {'nutrientId': 1257,
    'nutrientName': 'Fatty acids, total trans',
    'nutrientNumber': '605',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00875,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 15400,
    'indentLevel': 1,
    'foodNutrientId': 33295216,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.01,
    'median': 0.01},
   {'nutrientId': 1098,
    'nutrientName': 'Copper, Cu',
    'nutrientNumber': '312',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.00364,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6000,
    'indentLevel': 1,
    'foodNutrientId': 33295217,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0291,
    'median': 0.0},
   {'nutrientId': 1002,
    'nutrientName': 'Nitrogen',
    'nutrientNumber': '202',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 3.6,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 500,
    'indentLevel': 1,
    'foodNutrientId': 33295218,
    'dataPoints': 8,
    'min': 3.45,
    'max': 3.74,
    'median': 3.6},
   {'nutrientId': 1258,
    'nutrientName': 'Fatty acids, total saturated',
    'nutrientNumber': '606',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.349,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 9700,
    'indentLevel': 1,
    'foodNutrientId': 33295219,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.6,
    'median': 0.34},
   {'nutrientId': 1004,
    'nutrientName': 'Total lipid (fat)',
    'nutrientNumber': '204',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 1.93,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 800,
    'indentLevel': 1,
    'foodNutrientId': 33295220,
    'dataPoints': 8,
    'min': 1.31,
    'max': 3.1,
    'median': 1.71},
   {'nutrientId': 1292,
    'nutrientName': 'Fatty acids, total monounsaturated',
    'nutrientNumber': '645',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.369,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 11400,
    'indentLevel': 1,
    'foodNutrientId': 33295221,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.71,
    'median': 0.335},
   {'nutrientId': 1101,
    'nutrientName': 'Manganese, Mn',
    'nutrientNumber': '315',
    'unitName': 'MG',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.0,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 6100,
    'indentLevel': 1,
    'foodNutrientId': 33295222,
    'dataPoints': 8,
    'min': 0.0,
    'max': 0.0,
    'median': 0.0},
   {'nutrientId': 1293,
    'nutrientName': 'Fatty acids, total polyunsaturated',
    'nutrientNumber': '646',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,
    'value': 0.296,
    'foodNutrientSourceId': 1,
    'foodNutrientSourceCode': '1',
    'foodNutrientSourceDescription': 'Analytical or derived from analytical',
    'rank': 12900,
    'indentLevel': 1,
    'foodNutrientId': 33295223,
    'dataPoints': 8,
    'min': 0.19,
    'max': 0.55,
    'median': 0.275},
   {'nutrientId': 1007,
    'nutrientName': 'Ash',
    'nutrientNumber': '207',
    'unitName': 'G',
    'derivationCode': 'A',
    'derivationDescription': 'Analytical',
    'derivationId': 1,

In [52]:
df = pd.DataFrame.from_dict(data['foods'])

In [53]:
df

,fdcId,description,commonNames,additionalDescriptions,dataType,ndbNumber,publishedDate,foodCategory,mostRecentAcquisitionDate,allHighlightFields,score,microbes,foodNutrients,finalFoodInputFoods,foodMeasures,foodAttributes,foodAttributeTypes,foodVersionIds
0,2514746,"Chicken, ground, with additives, raw",,,Foundation,5332,2023-04-20,Poultry Products,2023-01-09,,201.99571,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
1,2646170,"Chicken, breast, boneless, skinless, raw",,,Foundation,100304,2023-10-26,Poultry Products,2023-04-03,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
2,2727569,"Chicken, breast, meat and skin, raw",,,Foundation,100375,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
3,2727566,"Chicken, drumstick, meat and skin, raw",,,Foundation,100372,2025-04-24,Poultry Products,2024-10-13,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
4,2646171,"Chicken, thigh, boneless, skinless, raw",,,Foundation,100305,2023-10-26,Poultry Products,2023-03-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
5,2727567,"Chicken, thigh, meat and skin, raw",,,Foundation,100373,2025-04-24,Poultry Products,2024-10-20,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
6,2727568,"Chicken, wing, meat and skin, raw",,,Foundation,100374,2025-04-24,Poultry Products,2024-10-27,,187.15979,[],"[{'nutrientId': 1089, 'nutrientName': 'Iron, F...",[],[],[],[],[]
7,331897,"Chicken, broilers or fryers, drumstick, meat o...",,,Foundation,5671,2019-04-01,Poultry Products,2010-05-11,,153.41048,[],"[{'nutrientId': 1253, 'nutrientName': 'Cholest...",[],[],[],[],[]
8,331960,"Chicken, broiler or fryers, breast, skinless, ...",,,Foundation,5746,2019-04-01,Poultry Products,2012-11-12,,136.97621,[],"[{'nutrientId': 1170, 'nutrientName': 'Pantoth...",[],[],[],[],[]

In [58]:
pd.DataFrame.from_dict(data['foods'][3]['foodNutrients'])

,nutrientId,nutrientName,nutrientNumber,unitName,derivationCode,derivationDescription,derivationId,value,foodNutrientSourceId,foodNutrientSourceCode,foodNutrientSourceDescription,rank,indentLevel,foodNutrientId,dataPoints,min,max,median
0,1089,"Iron, Fe",303,MG,A,Analytical,1,0.66600,1,1,Analytical or derived from analytical,5400,1,34678174,8.0,0.594,0.8780,0.63800
1,1090,"Magnesium, Mg",304,MG,A,Analytical,1,18.60000,1,1,Analytical or derived from analytical,5500,1,34678175,8.0,16.800,20.1000,18.90000
2,1091,"Phosphorus, P",305,MG,A,Analytical,1,152.00000,1,1,Analytical or derived from analytical,5600,1,34678176,8.0,137.000,164.0000,156.00000
3,1092,"Potassium, K",306,MG,A,Analytical,1,244.00000,1,1,Analytical or derived from analytical,5700,1,34678177,8.0,212.000,277.0000,246.00000
4,1253,Cholesterol,601,MG,A,Analytical,1,94.60000,1,1,Analytical or derived from analytical,15700,1,34678178,8.0,88.600,101.0000,92.50000
5,1093,"Sodium, Na",307,MG,A,Analytical,1,91.00000,1,1,Analytical or derived from analytical,5800,1,34678179,8.0,85.300,96.6000,91.00000
6,1095,"Zinc, Zn",309,MG,A,Analytical,1,1.70000,1,1,Analytical or derived from analytical,5900,1,34678180,8.0,1.570,1.8000,1.72000
7,1098,"Copper, Cu",312,MG,A,Analytical,1,0.04430,1,1,Analytical or derived from analytical,6000,1,34678181,8.0,0.036,0.0485,0.04570
8,1002,Nitrogen,202,G,A,Analytical,1,2.94000,1,1,Analytical or derived from analytical,500,1,34678182,8.0,2.750,3.1000,2.91000
9,1004,Total lipid (fat),204,G,A,Analytical,1,5.94000,1,1,Analytical or derived from analytical,800,1,34678183,8.0,5.010,6.8400,5.82000
10,1101,"Manganese, Mn",315,MG,A,Analytical,1,0.00655,1,1,Analytical or derived from analytical,6100,1,34678184,8.0,0.000,0.0142,0.00625
11,1007,Ash,207,G,A,Analytical,1,0.88900,1,1,Analytical or derived from analytical,1000,1,34678185,8.0,0.820,0.9600,0.89000
12,1051,Water,255,G,A,Analytical,1,75.30000,1,1,Analytical or derived from analytical,100,1,34678186,8.0,74.700,76.2000,75.20000
13,1087,"Calcium, Ca",301,MG,A,Analytical,1,8.28000,1,1,Analytical or derived from analytical,5300,1,34678187,8.0,6.930,10.2000,7.88000
14,1003,Protein,203,G,NC,Calculated,49,18.40000,2,4,Calculated or imputed,600,1,34678564,NaN,17.200,19.3000,18.20000
15,1005,"Carbohydrate, by difference",205,G,NC,Calculated,49,-0.47500,2,4,Calculated or imputed,1110,2,34678565,NaN,NaN,NaN,NaN
16,2047,Energy (Atwater General Factors),957,KCAL,NC,Calculated,49,125.00000,2,4,Calculated or imputed,280,1,34678566,NaN,NaN,NaN,NaN
17,2048,Energy (Atwater Specific Factors),958,KCAL,NC,Calculated,49,130.00000,2,4,Calculated or imputed,290,1,34678567,NaN,NaN,NaN,NaN